name: binf-7000-2024-spatial
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - anndata=0.10.9
  - anyio=4.4.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - array-api-compat=1.8
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cycler=0.12.1
  - debugpy=1.8.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.2
  - filelock=3.15.4
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - fsspec=2024.6.1
  - get-annotations=0.1.2
  - glpk=5.0
  - gprofiler-official=1.0.0
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.11.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.2
  - hyperframe=6.0.1
  - idna=3.8
  - igraph=0.10.13
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - importlib_resources=6.4.4
  - intel-openmp=2023.2.0
  - iprogress=0.4
  - ipykernel=6.29.5
  - ipython=8.27.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.15
  - legacy-api-wrap=1.4
  - leidenalg=0.10.2
  - lerc=4.0.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libdeflate=1.17
  - libexpat=2.6.2
  - libffi=3.4.4
  - libhwloc=2.11.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libleidenalg=0.11.1
  - libpng=1.6.43
  - libsodium=1.0.18
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libtiff=4.5.0
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvmlite=0.43.0
  - markupsafe=2.1.5
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - mkl=2023.2.0
  - mkl-service=2.4.1
  - mpir=3.0.0
  - mpmath=1.3.0
  - munkres=1.1.4
  - natsort=8.4.0
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.3
  - notebook-shim=0.2.4
  - numba=0.60.0
  - numpy=1.26.4
  - openjpeg=2.5.0
  - openssl=3.3.1
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=0.5.6
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pthreads-win32=2.9.1
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pynndescent=0.5.13
  - pyparsing=3.1.4
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-igraph=0.11.5
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytorch=2.3.0
  - pytz=2024.1
  - pywin32=306
  - pywinpty=2.0.13
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.0
  - scanpy=1.10.2
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - session-info=1.0.0
  - setuptools=72.1.0
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - stdlib-list=0.10.0
  - sympy=1.13.2
  - tbb=2021.12.0
  - terminado=0.18.1
  - texttable=1.7.0
  - threadpoolctl=3.5.0
  - tinycss2=1.3.0
  - tk=8.6.14
  - tomli=2.0.1
  - torchvision=0.18.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240821
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - umap-learn=0.5.6
  - uri-template=1.3.0
  - urllib3=2.2.2
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.1
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - flatbuffers==24.3.25
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.66.1
      - keras==3.5.0
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - namex==0.0.8
      - opt-einsum==3.3.0
      - optree==0.12.1
      - protobuf==4.25.4
      - rich==13.8.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-intel==2.17.0
      - termcolor==2.4.0
      - werkzeug==3.0.4
      - wrapt==1.16.0
